<a href="https://colab.research.google.com/github/noobylub/APCSA/blob/master/LELA60331_Week_4_Seminar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LELA60331 Computational Linguistics 1 Week 4

This week we are going to look at vector-based models of word meaning. I am first of all going to have to introduce  a Python library called Numpy (https://numpy.org/devdocs/user/absolute_beginners.html).

### Numpy

Numpy is widely used for representing and processing arrays, including multidimensional arrays (known to us as Vectors/Matrices/Tensors). It is fast, intuitive and has lots of helpful built-in functions (we will make use of some of these later in the semester).

To use numpy we need to import it as follows. The naming of numpy as np is a widely-used convention.

In [ ]:
import numpy as np

We can create empty numpy arrays as follows:

In [ ]:
# For a 1 dimensional colarray
p =   np.zeros(4)

In [ ]:
p

array([0., 0., 0., 0.])

In [ ]:
# For a 2 dimensional array
np.zeros((4, 5))

We can also create them from Python lists as follows:

In [ ]:
# Example vector
np.array([9,2,3,5])

In [ ]:
# Example rank 2 tensor (specificaly a 2x4 matrix)
np.array(([9,2,3,5],[4,6,7,3]))

In [ ]:
# Example rank 3 tensor 3x2x4
p= np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [ ]:
p

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

The arrays must be rectangular, not ragged, or you will see the following error

In [ ]:
# Example 3-dimensional array
np.array(([9,2,3,5],[4,6,7,3],[5,7,1,2,7]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

Just as with Python lists we can use indices to find individual values:

In [ ]:
a=np.array([9,2,3,5])
a[1]

And ranges:

In [ ]:
a[1:3]

We can do the same for multidimensional arrays. Indexes should be in the order of nesting. So for a rank 2 tensor the row index comes first and the column second:

In [ ]:
a=np.array(([9, 2, 3, 5],
       [4, 6, 7, 3],
       [5, 7, 1, 2]))
a[1,0]

We can assign values to particular positions in our tensor using indices:

In [ ]:
a[0,0] = 1000
a[2,1] = 2000
print(a)

For vectors we can perform the operations that we learned about in our lecture as follows:

In [ ]:
# Vector addition
a = np.array(([9,2,3,5]))
b = np.array(([1,2,3,4]))
c=a+b
print(a)
print(b)
print(c)

In [ ]:
# Vector subtraction
a = np.array(([9,2,3,5]))
b = np.array(([1,2,3,4]))
c=a-b
print(a)
print(b)
print(c)

In [ ]:
# Dot product
a = np.array(([9,2,3,5]))
b = np.array(([1,2,3,4]))
c=a*b
dp=sum(c)
print(a)
print(b)
print(c)
print(dp)

Problem 1: Write the code to calculate the cosine of the angle between vector a and vector b. You might need to refer to your lecture notes

In [7]:
import numpy as np

a = np.array(([9,2,3,5]))
b = np.array(([1,2,3,4]))
magnitude = np.linalg.norm(a)

magnitude2 = np.linalg.norm(b)
cosine_similairty = sum(a *b ) / (magnitude * magnitude2)


In [8]:
cosine_similairty

np.float64(0.7029350233548073)

### Building Word Vectors

In [9]:
import re
# download from from the internt
!wget https://www.gutenberg.org/files/2554/2554-0.txt
# Or in Jupyter
#from urllib.request import urlretrieve
#url = "https://www.gutenberg.org/files/2554/2554-0.txt"
#filename="2554-0.txt"
#urlretrieve(url, filename)
# read in the file
f = open('2554-0.txt')
c_and_p = f.read()
# select the first chapter - possible because I determined range
c_and_p = c_and_p[5464:]
# convert text to lower case
c_and_p=c_and_p.lower()
c_and_p=re.sub('\n',' ', c_and_p)
c_and_p=re.sub('[^a-z ]','', c_and_p)
c_and_p=re.split(" ", c_and_p)

--2025-10-20 13:32:58--  https://www.gutenberg.org/files/2554/2554-0.txt
Resolving www.gutenberg.org (www.gutenberg.org)... 152.19.134.47, 2610:28:3090:3000:0:bad:cafe:47
Connecting to www.gutenberg.org (www.gutenberg.org)|152.19.134.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1159923 (1.1M) [text/plain]
Saving to: ‘2554-0.txt’

2554-0.txt          100%[===================>]   1.11M  3.64MB/s    in 0.3s    

2025-10-20 13:32:59 (3.64 MB/s) - ‘2554-0.txt’ saved [1159923/1159923]



In [10]:
c_and_p[1:10]

['time', 'past', 'he', 'had', 'been', 'in', 'an', 'overstrained', 'irritable']

Problem 2 (to be tackled collectively): Write code to create a word-by-word matrix

In [20]:
token_count = len(c_and_p)
type_list = list(set(c_and_p))
# The type count is the number of unique words. The token count is the total number of words including repetitions.
type_count = len(type_list)
# We create a matrix in which to store the counts for each word-by-word co-occurence
M = np.zeros((type_count, type_count))
window_size = 2
rows, columns = M.shape
# COMPLETE CODE

In [23]:
M

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Problem 3: Calculate the cosine between "walk" and "run", and between "walk" and "shine". What does the outcome tell us?

In [ ]:
w1 = "walk"
w2 = "run"
w3 = "shine"
w1_index = type_list.index(w1)
w2_index = type_list.index(w2)
w3_index = type_list.index(w3)

### Pretrained embeddings

Vectors are best when learned from very large text collections. However learning such vectors, particularly using neural network methods rather than simple counting, is very computationally intensive. As a result most people make use of pretrained embeddings such as those found at

https://code.google.com/archive/p/word2vec/

or

https://nlp.stanford.edu/projects/glove/

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
#from urllib.request import urlretrieve
#url = "http://nlp.stanford.edu/data/glove.6B.zip"
#filename="glove.6B.zip"
#urlretrieve(url, filename)
!unzip -q glove.6B.zip

In [ ]:
import numpy as np
embedding_file = 'glove.6B.100d.txt'
#embedding_file = f.read()
embeddings=[]
type_list=[]
with open(embedding_file) as fp:
            for line in fp.readlines():
                line = line.split(" ")
                word = line[0]
                vec = np.array([float(x) for x in line[1:]])
                type_list.append(word)
                embeddings.append(vec)
M=np.array((embeddings))

In [ ]:
w1 = "football"
w2 = "rugby"
w3 = "cricket"
w1_index = type_list.index(w1)
w2_index = type_list.index(w2)
w3_index = type_list.index(w3)
w1_vec=M[w1_index,]
w2_vec=M[w2_index,]
w3_vec=M[w3_index,]

Problem 3. Calculate the cosine between the words above. What do the cosine values tell us?

# Finding the most similar words

One thing we often want to do is to find the most similar words to a given word/vector. An exhaustive N x N comparison is very time consuming, and so we can make use of an efficient "nearest neighbours" finding algorithm. We are just using this algorithm here so we won't go into it in any detail. We use the implementation in the Scikitlearn toolkit, which we will learn more about in the Python programming sessions in RM in CCL 2.

In [ ]:
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=5, algorithm='ball_tree').fit(M)

In [ ]:
w="football"
w_index = type_list.index(w)
w_vec = M[w_index,]
for i in nbrs.kneighbors([w_vec])[1][0]:
  print(type_list[i])

Problem 4. Find some examples where the system fails and explain why you think it has done so.

### Analogical reasoning

Another semantic property of embeddings is their ability to capture relational meanings. In an important early vector space model of cognition, Rumelhart and Abrahamson (1973) proposed the parallelogram model for solving simple analogy problems of the form a is to b as a* is to what?. In such problems, a system given a problem like apple:tree::grape:?, i.e., apple is to tree as  grape is to , and must fill in the word vine.

In the parallelogram model, the vector from the word apple to the word tree (= tree − apple) is added to the vector for grape (grape); the nearest word to that point is returned.





Problem 4: Complete the code below so that it solves the analogical reasoning problem. Come up with a analogical reasoning problem of your own and use the code to solve it.

In [ ]:
w1 = "apple"
w2 = "tree"
w3 = "grape"
w1_index = type_list.index(w1)
w2_index = type_list.index(w2)
w3_index = type_list.index(w3)
w1_vec = M[w1_index,]
w2_vec = M[w2_index,]
w3_vec = M[w3_index,]

spatial_relationship = ???
w4_vec = ???
nbrs.kneighbors([w4_vec])
for i in nbrs.kneighbors([w4_vec])[1][0]:
  print(type_list[i])